### ISSUE TITLE
Cask changelogs open twice

### ISSUE THREAD

**Issue by michaelblyons** [danielbayley/homebrew-changelog#10]
Run `brew cask changelog firefox`, and you get two new tabs.

**Comment by danielbayley** [comment]
@michaelblyons Sorry I can't reproduce… is it still happening, do you have more details? OS… default browser?

**Comment by michaelblyons** [comment]
Default browser is Chrome. I'm on Catalina now, but I first noticed on Mojave.

If there's a convenient way to get a debug log, I'm happy to.

**Comment by michaelblyons** [comment]
I don't imagine this is super helpful, but it opens _all_ the args' changelogs once; then opens them again. (As opposed to opening one twice; then the next one twice.)

```
$ brew cask changelog --debug firefox firefox-beta
==> Opening changelog for Cask firefox
==> Opening changelog for Cask firefox-beta
/usr/bin/open -- https://mozilla.org/en-US/firefox/releases
/usr/bin/open -- https://mozilla.org/en-US/firefox/beta/notes
==> Opening changelog for Cask firefox
==> Opening changelog for Cask firefox-beta
/usr/bin/open -- https://mozilla.org/en-US/firefox/releases
/usr/bin/open -- https://mozilla.org/en-US/firefox/beta/notes
```

**Comment by danielbayley** [comment]
@michaelblyons As mentioned in #12, I just pushed the refactoring I've been doing as and when… Should be much improved now! So feel free to test…
