### ISSUE TITLE
Broken after recent update

### ISSUE THREAD

**Issue by Zifius** [danielbayley/homebrew-changelog#14]
Hi @danielbayley,

after recent refactoring the tap got broken for me with the following trace:
```
brew changelog composer
Error: cannot load such file -- /opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/lib/utils
/opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:6:in `require_relative'
/opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:6:in `<top (required)>'
/opt/homebrew/Library/Homebrew/utils.rb:92:in `require'
/opt/homebrew/Library/Homebrew/utils.rb:92:in `require?'
/opt/homebrew/Library/Homebrew/commands.rb:91:in `external_ruby_v2_cmd_path'
/opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```
is it something you are aware of or a local issue?
Thank you

**Comment by danielbayley** [comment]
> Hi @danielbayley,
> 
> after recent refactoring the tap got broken for me with the following trace:
> 
> ```
> brew changelog composer
> Error: cannot load such file -- /opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/lib/utils
> /opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:6:in `require_relative'
> /opt/homebrew/Library/Taps/danielbayley/homebrew-changelog/cmd/changelog.rb:6:in `<top (required)>'
> /opt/homebrew/Library/Homebrew/utils.rb:92:in `require'
> /opt/homebrew/Library/Homebrew/utils.rb:92:in `require?'
> /opt/homebrew/Library/Homebrew/commands.rb:91:in `external_ruby_v2_cmd_path'
> /opt/homebrew/Library/Homebrew/brew.rb:89:in `<main>'
> ```
> 
> is it something you are aware of or a local issue? Thank you

@Zifius Should be fixed now!
